---

## resources

# http://docs.ansible.com/ansible/intro_windows.html
# * get dependancies from site above.

## Create vault

# ansible-vault edit group_vars/windows.yml

## test

# ansible windows [-i inventory] -m win_ping --ask-vault-pass

# These should all go in an encrypted ansible-vault:

ansible_user: Administrator
ansible_password: SecretPasswordGoesHere
ansible_port: 5986
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ when using default WinRM self-signed certificates:
ansible_winrm_server_cert_validation: ignore
