---
- hosts: all
  become: true
#  gather_facts: false
  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=43200
      tags: [ 'packages' ]

#- include: ansible-rsync
- include: maestro.yml

