---
# file: maestro/handlers/main.yml

- name: restart ssh
  service: name=ssh state=restarted

- name: disable ufw
  service: name=ufw state=stopped enabled=no

- name: start ufw
  service: name=ufw state=started enabled=yes

- name: start shorewall
  service: name=shorewall state=started
