---
# Example that prints the loopback address and gateway for each host
- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- debug: msg="System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
  when: ansible_default_ipv4.gateway is defined

- shell: /usr/bin/uptime
  register: result

- debug: var=result

- name: Display all variables/facts known for a host
  debug: var=hostvars[inventory_hostname]

# Add gnome3

- name: Add the gnome3 repository
  apt_repository: repo='ppa:gnome3-team/gnome3' state=present
  tags: [ 'packages', 'gnome_3' ]

- name: update apt cache
  apt: update_cache=yes cache_valid_time=43200
  tags: [ 'packages', 'gnome_3' ]

- name: Install packages, variables defined in ../default/main.yml
  apt: name={{ item }} state=present
  with_flattened:
     - "{{ gnome_3_debs }}"
  tags: [ 'packages', 'gnome_3' ]

